name: tri_reid
channels:
  - nvidia/label/cuda-12.1.1
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip=25.2
  - setuptools=83.0.0
  - wheel=0.47.0
  - cuda-cccl=12.1.109
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-nvcc=12.1.105
  - pip:
      - -r requirements-lock.txt
